# -*- coding: utf-8 -*-
"""Task 5: Sales Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-ZxS-l8MbD1zwUGKKpDgUuxJl-n12Zu
"""

# ==========================================
# SUPERSTORE SALES ANALYSIS PROJECT (FIXED)
# ==========================================

!pip install pandas matplotlib openpyxl -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import zipfile
import os
import time

plt.style.use('ggplot')

print("Upload Superstore Dataset ZIP or CSV File")

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# ==========================================
# LOAD DATA
# ==========================================

if file_name.endswith('.zip'):

    with zipfile.ZipFile(file_name, 'r') as zip_ref:
        zip_ref.extractall()

    csv_files = [f for f in os.listdir() if f.endswith('.csv')]

    if len(csv_files) == 0:
        raise Exception("No CSV file found inside ZIP")

    df = pd.read_csv(csv_files[0], encoding='latin1')

else:
    df = pd.read_csv(file_name, encoding='latin1')

print("\nDataset Uploaded Successfully")

print("\nFirst 5 Rows")
print(df.head())

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

# ==========================================
# DATE CONVERSION
# ==========================================

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')
df['Month_Year'] = df['Order Date'].dt.to_period('M')

# ==========================================
# MONTHLY SALES
# ==========================================

monthly_sales = df.groupby('Month_Year')['Sales'].sum()

print("\nMonthly Revenue Trend")
print(monthly_sales)

plt.figure(figsize=(14,6))
monthly_sales.plot(marker='o', linewidth=3)

plt.title('Monthly Revenue Trend', fontsize=18, fontweight='bold')
plt.xlabel('Month-Year', fontsize=14)
plt.ylabel('Revenue', fontsize=14)
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.savefig('monthly_revenue_trend.png', dpi=300)
plt.show()

# ==========================================
# TOP PRODUCTS
# ==========================================

top_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

print("\nTop Selling Products")
print(top_products)

plt.figure(figsize=(14,7))
top_products.sort_values().plot(kind='barh')

plt.title('Top 10 Selling Products', fontsize=18, fontweight='bold')
plt.xlabel('Sales', fontsize=14)
plt.ylabel('Products', fontsize=14)

plt.tight_layout()
plt.savefig('top_selling_products.png', dpi=300)
plt.show()

# ==========================================
# PROFIT ANALYSIS (SAFE)
# ==========================================

total_profit = None
profit_by_category = None

if 'Profit' in df.columns:

    profit_by_category = df.groupby('Category')['Profit'].sum()

    print("\nProfit by Category")
    print(profit_by_category)

    plt.figure(figsize=(10,6))
    profit_by_category.plot(kind='bar')

    plt.title('Profit Analysis by Category', fontsize=18, fontweight='bold')
    plt.xlabel('Category', fontsize=14)
    plt.ylabel('Profit', fontsize=14)

    plt.tight_layout()
    plt.savefig('profit_analysis.png', dpi=300)
    plt.show()

# ==========================================
# SALES BY REGION
# ==========================================

region_sales = df.groupby('Region')['Sales'].sum()

print("\nSales by Region")
print(region_sales)

plt.figure(figsize=(10,6))

plt.pie(region_sales, labels=region_sales.index, autopct='%1.1f%%', startangle=90)

plt.title('Sales Distribution by Region', fontsize=18, fontweight='bold')

plt.tight_layout()
plt.savefig('sales_by_region.png', dpi=300)
plt.show()

# ==========================================
# TOTAL SALES & PROFIT (FIXED)
# ==========================================

total_sales = df['Sales'].sum()

print("\nTotal Sales:", total_sales)

if 'Profit' in df.columns:
    total_profit = df['Profit'].sum()
    print("Total Profit:", total_profit)
else:
    print("Profit column not available in dataset")

# ==========================================
# SAVE FILES
# ==========================================

monthly_sales.to_csv('monthly_sales.csv')
top_products.to_csv('top_products.csv')
region_sales.to_csv('region_sales.csv')

if profit_by_category is not None:
    profit_by_category.to_csv('profit_analysis.csv')

# ==========================================
# REPORT (FIXED ERROR)
# ==========================================

report = f"""
==========================================
BUSINESS INSIGHTS REPORT
==========================================

1. Total Sales:
{total_sales}

2. Total Profit:
{total_profit if total_profit is not None else "Not Available"}

3. Top Selling Products:
{top_products}

4. Sales by Region:
{region_sales}

5. Business Insights:

- Monthly revenue trends show business growth patterns.
- Top products generate maximum revenue.
- Regional performance highlights strong markets.
- Profit analysis (if available) shows category performance.

==========================================
Analysis Completed Successfully
==========================================
"""

with open("business_insights_report.txt", "w") as f:
    f.write(report)

print("\nBusiness Report Created")

# ==========================================
# CREATE ZIP FILE
# ==========================================

files_to_zip = [
    'monthly_sales.csv',
    'top_selling_products.png',
    'monthly_revenue_trend.png',
    'sales_by_region.png',
    'top_products.csv',
    'region_sales.csv',
    'business_insights_report.txt'
]

if profit_by_category is not None:
    files_to_zip.append('profit_analysis.csv')
    files_to_zip.append('profit_analysis.png')

zip_file_name = "Superstore_Analysis_Output.zip"

with zipfile.ZipFile(zip_file_name, 'w') as zipf:
    for file in files_to_zip:
        if os.path.exists(file):
            zipf.write(file)

print("\nZIP File Created Successfully")

# ==========================================
# DOWNLOAD
# ==========================================

files.download(zip_file_name)

print("\nAll Files Downloaded Successfully")